name: oxygen
description: A lightweight Entity Component System framework written in Dart
version: 0.2.0
homepage: https://github.com/flame-engine/oxygen

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  benchmark: ^0.3.0
  flame_lint: ^0.0.1
  mocktail: ^0.3.0
  test: ^1.20.2
