name: oxygen
description: A lightweight Entity Component System framework written in Dart
version: 0.1.0
homepage: https://github.com/flame-engine/oxygen

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.7
  benchmark: ^0.2.1
  pedantic: ^1.9.2
