name: oxygen
description: A lightweight Entity Component System framework written in Dart
version: 0.3.0
homepage: https://github.com/flame-engine/oxygen

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.5
  benchmark: ^0.3.0
  pedantic: ^1.11.0
