blank_issues_enabled: true
contact_links:
  - name: I have some questions about Oxygen.
    url: https://stackoverflow.com/tags/oxygen
    about: Ask your questions on StackOverflow! The community is always willing to help out.